driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096
  synced_folders:
    - ['.', '/home/vagrant/oneacct-export']

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.4.0

platforms:
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: centos-6.5
  - name: centos-7.1
    run_list: yum-epel::default
  - name: debian-7.6
    run_list: apt::default
  - name: debian-8.2
    run_list: apt::default

suites:
  - name: default
    run_list:
      - resolver::default
      - omnibus::default
      - omnibus-build::default
    attributes:
      omnibus:
        build_user:  vagrant
        build_dir:   /home/vagrant/oneacct-export
        install_dir: /opt/oneacct-export
      resolver:
        nameservers:
          - 8.8.8.8
          - 147.251.4.33
          - 147.251.6.10
        search: ics.muni.cz
